# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    # docker:
    #   # specify the version
    #   - image: circleci/golang:1.9

    #   # Specify service dependencies here if necessary
    #   # CircleCI maintains a library of pre-built images
    #   # documented at https://circleci.com/docs/2.0/circleci-images/
    #   # - image: circleci/postgres:9.4

    # #### TEMPLATE_NOTE: go expects specific checkout path representing url
    # #### expecting it in the form of
    # ####   /go/src/github.com/circleci/go-tool
    # ####   /go/src/bitbucket.org/circleci/go-tool
    # working_directory: /go/src/github.com/DVC-Software/apiserver
    # steps:
    #   - checkout

    #   # specify any bash command here prefixed with `run: `
    #   - run: go get -v -t -d ./...
    #   - run: go test -v ./...
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker info
      - run: docker-compose --version
      # Remove all existing docker images
      - run:
          name: Remove all docker images
          command: |
            make rm-all
      # Initiaize mysql db
      - run:
          name: Initialize database
          command: |
            make init-db
      # Test
      - run:
          name: Run Tests
          command: |
            make test

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
