version: '3'
services:
  db:
    build:
      context: ../mysql
    environment:
      MYSQL_ROOT_PASSWORD: dvcsoftware
      MYSQL_DATABASE: dvc_api_server
      MYSQL_USER: dvcsoftware
      MYSQL_PASSWORD: dvcsoftware
    container_name: dvc_mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -c2 -h localhost"
      interval: 10s
      timeout: 10s
      retries: 30
    restart: always
    tty: true
    volumes:
      - mysqldata:/var/lib/mysql
  
  dvc_api_server:
    build:
      context: ..
    container_name: dvc_api_server
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
  
volumes:
  mysqldata:
    driver: local