FROM mysql/mysql-server:latest

COPY init.sql /init/

# RUN mysql.server start

# RUN mysql -h 127.0.0.1 -P 3306 -uroot -pdvcsoftware mysql

# RUN mysql>CREATE DATABASE dvc_api_server

# RUN mysql -uroot -pdvcsoftware dvc_api_server < init/init.sql